# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  snyk: snyk/snyk@0.0.8

jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/python:3.7.1

    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          make zip
          set +o pipefail
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          set -o pipefail
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          VERSION_NUMBER=$(echo $VERSION | sed 's/^v\(.*\)$/\1/')
          mv emr-launcher.zip emr-launcher-$VERSION_NUMBER.zip

    - persist_to_workspace:
        root: .
        paths:
        - emr-launcher-*.zip
        - Pipfile

  snyk-pr:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          # Snyk is supposed to do this automatically but it doesn't, so we manually install dependencies to be tested
          name: Install dependencies
          command: |
            pipenv install
      - snyk/scan:
          organization: dwp-dataworks
          severity-threshold: high
          target-file: Pipfile
          project: '${CIRCLE_PROJECT_REPONAME}/pr-emr-launcher'

  snyk-master:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          # Snyk is supposed to do this automatically but it doesn't, so we manually install dependencies to be tested
          name: Install dependencies
          command: |
            pipenv install
      - snyk/scan:
          organization: dwp-dataworks
          severity-threshold: high
          target-file: Pipfile
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-emr-laucher'

  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: .
    - run:
        name: "Publish Release on GitHub"
        command: |
          set -u
          set +o pipefail
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          set -o pipefail
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "ghr -t GITHUB_TOKEN -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ."
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} .

workflows:
  version: 2
  build-and-publish:
    jobs:
    - build
    - snyk-pr:
        requires:
        - build
        filters:
          branches:
            ignore: master
    - snyk-master:
        requires:
          - build
        filters:
          branches:
            only: master
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            only: master
