name: Master

on:
  push:
    branches:
      - mastercopy
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build-app:
    runs-on: ubuntu-latest
    needs: [get-publish-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          make zip
          set +o pipefail
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          set -o pipefail
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          VERSION_NUMBER=$(echo $VERSION | sed 's/^v\(.*\)$/\1/')
          echo $VERSION_NUMBER > version && zip -ur emr-launcher.zip version

      - name: Run tests
        run: |
          pip install -r requirements.txt
          python -m pytest -v

      - uses: actions/upload-artifact@v3
        with:
          name: Pipfile
          path: /home/runner/work/emr-launcher/emr-launcher/Pipfile

      - uses: actions/upload-artifact@v3
        with:
          name: emr-launcher.zip
          path: emr-launcher.zip


  get-publish-version:
    runs-on: ubuntu-latest
    outputs:
      publish-version: ${{ steps.get-publish-version.outputs.publish-version }}
    steps:
      - name: Prepare SemVer
        id: prepare-semver
        run: |
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          echo "latest_version_out=$LATEST_VERSION" >> $GITHUB_OUTPUT
          commit_message=$( echo "${{ github.event.head_commit.message }}" | sed 's/"//g')
          if [[ "${commit_message,,}" == *"major release"* ]]; then
            echo "semver_increment='m'" >> $GITHUB_OUTPUT
          elif [[ "${commit_message,,}" == *"minor release"* ]]; then
            echo "semver_increment='i'" >> $GITHUB_OUTPUT
          else
            echo "semver_increment='p'" >> $GITHUB_OUTPUT
          fi
      
      - name: Increment SemVer
        id: semver
        uses: matt-FFFFFF/simple-semver@v0.1.0
        with:
          semver-input: ${{ steps.prepare-semver.outputs.latest_version_out }}
          increment: ${{ steps.prepare-semver.outputs.semver_increment }}
      
      - name: Get publish version
        id: get-publish-version
        run: |
          echo "publish-version=${{ steps.semver.outputs.semver }}" >> $GITHUB_OUTPUT
  
  
  publish-github-release:
    runs-on: ubuntu-latest
    needs: [build-app, get-publish-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download EMRLauncher
        uses: actions/download-artifact@v3
        with:
          name: emr-launcher-$publish-version.zip

      - name: Download Pifile
        uses: actions/download-artifact@v3
        with:
          name: Pipfile
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.get-publish-version.outputs.publish-version }}
          release_name: ${{ needs.get-publish-version.outputs.publish-version }}
          draft: false
          prerelease: false

      - name: upload emr-launcher file
        uses: actions/upload-release-asset@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emr-launcher.zip
          asset_name: emr-launcher-$publish_version.zip

      - name: upload Pipfile
        uses: actions/upload-release-asset@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Pipfile
          asset_name: Pipfile
